Fix createSession design. NativeBase now used as intended as an out o…
IT2810/it2810-webutvikling-h18-prosjekt-3-50 pull request #29
Opened 2018-10-05 17:12 UTC by Mariusun

…f the box module, this fixes SafeArea bugs on iPhoneX. Also includes bugfix for number of days ago.

2018-10-07 12:19 UTC, teatimes requested changes

2018-10-07 12:19 UTC, teatimes commented on App.js
> +import { getTheme, material, Button, Container, Header, Icon, StyleProvider, Root} from 'native-base'
Don't think getTheme and material is necessary if native-base-theme folder is removed?

2018-10-07 12:19 UTC, teatimes commented on src/components/CreateSession.js
> +          <View style={styles.exerciseListConatiner}>
Spelling mistake: should be exerciseListContainer, not exerciseListConatiner. 

Same goes for contactListConatiner

2018-10-07 12:19 UTC, teatimes commented on src/components/CreateSession.js
> +  exerciseListConatiner: {
Spelling mistake

2018-10-07 12:19 UTC, teatimes commented on src/components/CreateSession.js
> +  contactListConatiner: {
Spelling mistake

2018-10-07 12:19 UTC, teatimes commented on src/components/ExerciseList.js
> -  showToast() {
Why remove this?

2018-10-07 12:19 UTC, teatimes commented on src/components/Home.js
> +      <SafeAreaView>
What does SafeAreaView do?

2018-10-07 12:19 UTC, teatimes commented on src/components/ShowSession.js
> +        <Moment element={Text} format="D. MMMM">
D. MMMM ?

2018-10-07 12:19 UTC, teatimes commented on src/components/ShowSession.js
> +    <Moment element={Text} fromNow={new Date() > dateTime} toNow={new Date() <= dateTime}>
Smart!

2018-10-07 12:19 UTC, teatimes commented on src/components/ContactList.js
> -      <Picker.Item label='Add a contact' value='0' key="0" />
Needed to have an empty element selected, so that they don't have to select any if they click on the list and don't find the contact

2018-10-07 12:19 UTC, teatimes commented on src/components/ContactList.js
> +    fontWeight: '600'
Personally I find the font way to big (goes for all headers in CreateSession, ContactList and ExerciseList)

2018-10-07 12:19 UTC, teatimes commented on src/components/ContactList.js
>          <Row style={{marginTop: 16}}>
I'm not sure why, but adding and removing contacts do not work anymore. If you try to add one, you add all and the dropdown list stops working. If you try to delete it, something happens in the dropdown list, and the element seems to be added as soon as it is deleted.

2018-10-07 12:19 UTC, teatimes commented on src/components/ContactList.js
> +          {this.state.addedContacts.map((contact, index) => (
Why not use dataArray and renderRow?

2018-10-08 11:57 UTC, Mariusun commented on src/components/ExerciseList.js
> -  showToast() {
The exercise immediately disappears from the list. This informs the user of a successful action. The toast turns up and confirms something the user already knows and is more of a distraction/in the way than helpful imo.

2018-10-08 11:57 UTC, Mariusun commented on src/components/Home.js
> +      <SafeAreaView>
iPhoneX padding for the notch

2018-10-08 11:59 UTC, Mariusun commented on src/components/ShowSession.js
> +        <Moment element={Text} format="D. MMMM">
Prints the date as:   8. October
Instead of: 08.10

2018-10-08 12:01 UTC, Mariusun commented on src/components/ContactList.js
> -      <Picker.Item label='Add a contact' value='0' key="0" />
On iOS there is a back button in the top corner. Usually that means there is a back arrow on Android, but I guess not this time. Thinking to replace the Picker anyway with a custom built component in upcoming PR. Picking a contact element that isn't a contact is a confusing user experience.

2018-10-08 12:03 UTC, Mariusun commented on src/components/ContactList.js
> +    fontWeight: '600'
It is inspired by the new App Store design :P

2018-10-08 12:05 UTC, Mariusun commented on src/components/ContactList.js
>          <Row style={{marginTop: 16}}>
Works exactly as it should on iOS. As mentioned though I'm thinking to create a custom built component, and also updating state a bit differently with redux, so this can be ignored for now..

2018-10-08 12:07 UTC, Mariusun commented on src/components/ContactList.js
> +          {this.state.addedContacts.map((contact, index) => (
If I remember correctly, that is what caused the scroll within scroll? Anyway .map() with listItems works great!

2018-10-08 12:42 UTC, teatimes commented on src/components/ContactList.js
> -      <Picker.Item label='Add a contact' value='0' key="0" />
I don't get what you mean now. What do the backarrow have to do with this?

Why it is confusing to pick an empty element? If we talk about the same thing, it is normal to have an empty option that is also shown as a default when you open the list

2018-10-08 12:43 UTC, teatimes commented on src/components/ContactList.js
> +    fontWeight: '600'
Can you send a screenshow of that design on slack?

2018-10-08 12:43 UTC, teatimes commented on src/components/ContactList.js
>          <Row style={{marginTop: 16}}>
No, this can't be ignored because the tests will fail (at least should).

2018-10-08 12:44 UTC, teatimes commented on src/components/ContactList.js
> +          {this.state.addedContacts.map((contact, index) => (
I find that weird, since the dataArray is meant to let you avoid having to map it manually

2018-10-08 12:44 UTC, teatimes commented on src/components/ExerciseList.js
> -  showToast() {
I see you point, but I'm not sure if it should be removed. Can we leave it now, and rather remove it later?

2018-10-08 12:57 UTC, Mariusun commented on src/components/ContactList.js
> -      <Picker.Item label='Add a contact' value='0' key="0" />
-> If you don't find the contact, click the backarrow.

2018-10-08 12:58 UTC, Mariusun commented on src/components/ContactList.js
> +    fontWeight: '600'
Done

2018-10-09 19:03 UTC, teatimes approved these changes

2018-10-09 19:03 UTC, teatimes commented on src/components/CreateSession.js
> +            <ExerciseList />
Need to pass the navigation to Exercise, possibly also to contactList

2018-10-09 19:06 UTC, merged