Feat/#12 handle state
IT2810/it2810-webutvikling-h18-prosjekt-3-50 pull request #39
Opened 2018-10-14 18:48 UTC by teatimes

2018-10-15 13:44 UTC, Mariusun requested changes
Errors:
Choose not today's date, then create session, then add contact
Choose not today's date, then create session, then add exercise

Bugs:
Start fresh, click today's date -> session changes, but shouldn't
Newly created sessions do not show up

2018-10-15 13:44 UTC, Mariusun commented on reducers/sessions.js
> +    case 'ADD_SESSION':
Should import action types from actions/types.js

2018-10-15 13:44 UTC, Mariusun commented on src/components/AddContact.js
> +  availableContacts() {
This function is unused. Component currently has no prop contacts.

2018-10-15 13:44 UTC, Mariusun commented on src/components/CreateSession.js
>        date: propDate != null ? propDate : new Date(),
state.date and selectedDate from the store seem to store the same? Should only be in the store when of interest to other components, and be included as prop for the component in mapStateToProps.

2018-10-15 13:44 UTC, Mariusun commented on src/components/__tests__/AddContact.spec.js
> +    wrapper = shallow(<AddContact navigation={navigation} addExercise={dispatchAddContactMock} addContact={dispatchAddContactMock} />)
AddContact should not be given addExercise as prop

2018-10-15 19:24 UTC, teatimes commented on reducers/sessions.js
> +    case 'ADD_SESSION':
Import and use how, you mean?

2018-10-15 19:27 UTC, teatimes commented on src/components/AddContact.js
> +  availableContacts() {
The method is not implemented yet, just copied it from earlier so we don't have to rewrite it. Have commented it out for now

2018-10-16 10:45 UTC, Mariusun commented on reducers/sessions.js
> +    case 'ADD_SESSION':
Like in the reducers in e.g. this project: https://github.com/gothinkster/react-redux-realworld-example-app/blob/master/src/reducers/common.js

2018-10-16 10:52 UTC, teatimes commented on reducers/sessions.js
> +    case 'ADD_SESSION':
Is there any important reason to do it that way instead? It works as it is now, and I think I tried to do what you suggests, but then it just failed

2018-10-16 14:21 UTC, Mariusun commented on reducers/sessions.js
> +    case 'ADD_SESSION':
It's good practice, but if you encountered a problem just leave it as is.

2018-10-16 14:25 UTC, Mariusun approved these changes

2018-10-16 14:28 UTC, merged