Add Stats View
IT2810/it2810-webutvikling-h18-prosjekt-3-50 pull request #44
Opened 2018-10-15 10:25 UTC by Mariusun

2018-10-16 12:02 UTC, teatimes requested changes
Missing statistic regarding exercises. Stats button is just a white rectangle in the corner, moving outside of the screen.

2018-10-16 12:02 UTC, teatimes commented on src/components/Home.js
> +        title="Stats      " // whitespace = easiest way to create padding
But it won't be dynamic for different phones, so we should find another way

2018-10-16 14:56 UTC, Pederduel approved these changes

2018-10-17 07:14 UTC, teatimes approved these changes

2018-10-17 07:14 UTC, merged